// <auto-generated />
using System;
using ClimbSort.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClimbSort.Migrations
{
    [DbContext(typeof(ClimbSortDBContext))]
    partial class ClimbSortDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClimbSort.Core.Models.Circuit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Beginner")
                        .HasColumnType("bit");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Dangerous")
                        .HasColumnType("bit");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("ModifiedDate")
                        .IsDescending();

                    b.ToTable("Circuit", (string)null);
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Climb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CircuitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CircuitNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("CragId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Popularity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SearchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SitStart")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TopographyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WallTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.HasIndex("CragId");

                    b.HasIndex("GradeId");

                    b.HasIndex("ModifiedDate")
                        .IsDescending();

                    b.HasIndex("TopographyId");

                    b.HasIndex("WallTypeId");

                    b.ToTable("Climb", (string)null);
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Crag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedDate")
                        .IsDescending();

                    b.ToTable("Crag", (string)null);
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Generic.Coordinates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CircuitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClimbId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CoordinateType")
                        .HasColumnType("int");

                    b.Property<Guid?>("CragId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<Guid?>("TopographyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.HasIndex("ClimbId");

                    b.HasIndex("CragId");

                    b.HasIndex("TopographyId");

                    b.ToTable("Coordinates", (string)null);
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Generic.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ClimbId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CragId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TagTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClimbId");

                    b.HasIndex("CragId");

                    b.HasIndex("TagTypeId");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GradeLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradingSystemId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxDifficultyRank")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MeanDifficultyRank")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinDifficultyRank")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScaleOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradingSystemId");

                    b.HasIndex("ScaleOrder");

                    b.ToTable("Grade", (string)null);
                });

            modelBuilder.Entity("ClimbSort.Core.Models.GradingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Discipline")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GradingSystem", (string)null);
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Static.TagType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TagType", (string)null);
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Static.WallType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WallType", (string)null);
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Topography", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClimbId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClimbId");

                    b.HasIndex("ModifiedDate")
                        .IsDescending();

                    b.ToTable("Topography", (string)null);
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Circuit", b =>
                {
                    b.HasOne("ClimbSort.Core.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Climb", b =>
                {
                    b.HasOne("ClimbSort.Core.Models.Circuit", "Circuit")
                        .WithMany("Climbs")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClimbSort.Core.Models.Crag", "Crag")
                        .WithMany("Climbs")
                        .HasForeignKey("CragId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClimbSort.Core.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClimbSort.Core.Models.Topography", "Topography")
                        .WithMany()
                        .HasForeignKey("TopographyId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("ClimbSort.Core.Models.Static.WallType", "WallType")
                        .WithMany()
                        .HasForeignKey("WallTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Circuit");

                    b.Navigation("Crag");

                    b.Navigation("Grade");

                    b.Navigation("Topography");

                    b.Navigation("WallType");
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Generic.Coordinates", b =>
                {
                    b.HasOne("ClimbSort.Core.Models.Circuit", "Circuit")
                        .WithMany("Coordinates")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClimbSort.Core.Models.Climb", "Climb")
                        .WithMany("Coordinates")
                        .HasForeignKey("ClimbId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClimbSort.Core.Models.Crag", "Crag")
                        .WithMany("Coordinates")
                        .HasForeignKey("CragId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClimbSort.Core.Models.Topography", "Topography")
                        .WithMany("Coordinates")
                        .HasForeignKey("TopographyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Circuit");

                    b.Navigation("Climb");

                    b.Navigation("Crag");

                    b.Navigation("Topography");
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Generic.Tag", b =>
                {
                    b.HasOne("ClimbSort.Core.Models.Climb", "Climb")
                        .WithMany("Tags")
                        .HasForeignKey("ClimbId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClimbSort.Core.Models.Crag", "Crag")
                        .WithMany("Tags")
                        .HasForeignKey("CragId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClimbSort.Core.Models.Static.TagType", "TagType")
                        .WithMany("Tags")
                        .HasForeignKey("TagTypeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Climb");

                    b.Navigation("Crag");

                    b.Navigation("TagType");
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Grade", b =>
                {
                    b.HasOne("ClimbSort.Core.Models.GradingSystem", "GradingSystem")
                        .WithMany()
                        .HasForeignKey("GradingSystemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GradingSystem");
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Topography", b =>
                {
                    b.HasOne("ClimbSort.Core.Models.Climb", "Climb")
                        .WithMany()
                        .HasForeignKey("ClimbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Climb");
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Circuit", b =>
                {
                    b.Navigation("Climbs");

                    b.Navigation("Coordinates");
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Climb", b =>
                {
                    b.Navigation("Coordinates");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Crag", b =>
                {
                    b.Navigation("Climbs");

                    b.Navigation("Coordinates");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Static.TagType", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ClimbSort.Core.Models.Topography", b =>
                {
                    b.Navigation("Coordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
