// <auto-generated />
using System;
using FontRecommender.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FontRecommender.Migrations
{
    [DbContext(typeof(FontRecommendationDBContext))]
    [Migration("20260519231656_InitialStructure")]
    partial class InitialStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoordinatesCrag", b =>
                {
                    b.Property<int>("CoordinatesId")
                        .HasColumnType("int");

                    b.Property<Guid>("CragId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CoordinatesId", "CragId");

                    b.HasIndex("CragId");

                    b.ToTable("CoordinatesCrag");
                });

            modelBuilder.Entity("CoordinatesTopography", b =>
                {
                    b.Property<int>("CoordinatesId")
                        .HasColumnType("int");

                    b.Property<Guid>("TopographyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CoordinatesId", "TopographyId");

                    b.HasIndex("TopographyId");

                    b.ToTable("CoordinatesTopography");
                });

            modelBuilder.Entity("FontRecommender.Core.Models.Climb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CoordinatesId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CragId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CragId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int");

                    b.Property<int?>("GradeId1")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Popularity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("TopographyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WallTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatesId");

                    b.HasIndex("CragId");

                    b.HasIndex("CragId1");

                    b.HasIndex("GradeId");

                    b.HasIndex("GradeId1");

                    b.HasIndex("ModifiedDate")
                        .IsDescending();

                    b.HasIndex("TopographyId");

                    b.HasIndex("WallTypeId");

                    b.ToTable("Climb", (string)null);
                });

            modelBuilder.Entity("FontRecommender.Core.Models.Crag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedDate")
                        .IsDescending();

                    b.ToTable("Crag", (string)null);
                });

            modelBuilder.Entity("FontRecommender.Core.Models.Generic.Coordinates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoordinateType")
                        .HasColumnType("int");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Coordinates", (string)null);
                });

            modelBuilder.Entity("FontRecommender.Core.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Discipline")
                        .HasColumnType("int");

                    b.Property<string>("GradeLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradingSystemId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxDifficultyRank")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MeanDifficultyRank")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinDifficultyRank")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScaleOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradingSystemId");

                    b.HasIndex("ScaleOrder");

                    b.ToTable("Grade", (string)null);
                });

            modelBuilder.Entity("FontRecommender.Core.Models.GradingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GradingSystem", (string)null);
                });

            modelBuilder.Entity("FontRecommender.Core.Models.Topography", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedDate")
                        .IsDescending();

                    b.ToTable("Topography", (string)null);
                });

            modelBuilder.Entity("FontRecommender.Core.Models.WallType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WallType", (string)null);
                });

            modelBuilder.Entity("CoordinatesCrag", b =>
                {
                    b.HasOne("FontRecommender.Core.Models.Generic.Coordinates", null)
                        .WithMany()
                        .HasForeignKey("CoordinatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FontRecommender.Core.Models.Crag", null)
                        .WithMany()
                        .HasForeignKey("CragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoordinatesTopography", b =>
                {
                    b.HasOne("FontRecommender.Core.Models.Generic.Coordinates", null)
                        .WithMany()
                        .HasForeignKey("CoordinatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FontRecommender.Core.Models.Topography", null)
                        .WithMany()
                        .HasForeignKey("TopographyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FontRecommender.Core.Models.Climb", b =>
                {
                    b.HasOne("FontRecommender.Core.Models.Generic.Coordinates", "Coordinates")
                        .WithMany()
                        .HasForeignKey("CoordinatesId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FontRecommender.Core.Models.Crag", "Crag")
                        .WithMany()
                        .HasForeignKey("CragId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FontRecommender.Core.Models.Crag", null)
                        .WithMany("Climbs")
                        .HasForeignKey("CragId1");

                    b.HasOne("FontRecommender.Core.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FontRecommender.Core.Models.Grade", null)
                        .WithMany("Climbs")
                        .HasForeignKey("GradeId1");

                    b.HasOne("FontRecommender.Core.Models.Topography", "Topography")
                        .WithMany()
                        .HasForeignKey("TopographyId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("FontRecommender.Core.Models.WallType", "WallType")
                        .WithMany()
                        .HasForeignKey("WallTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Coordinates");

                    b.Navigation("Crag");

                    b.Navigation("Grade");

                    b.Navigation("Topography");

                    b.Navigation("WallType");
                });

            modelBuilder.Entity("FontRecommender.Core.Models.Grade", b =>
                {
                    b.HasOne("FontRecommender.Core.Models.GradingSystem", "GradingSystem")
                        .WithMany()
                        .HasForeignKey("GradingSystemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GradingSystem");
                });

            modelBuilder.Entity("FontRecommender.Core.Models.Crag", b =>
                {
                    b.Navigation("Climbs");
                });

            modelBuilder.Entity("FontRecommender.Core.Models.Grade", b =>
                {
                    b.Navigation("Climbs");
                });
#pragma warning restore 612, 618
        }
    }
}
